ecommercedress/ecommercedress/fashionstore/cart_app/urls.py
from django.urls import path
from . import views


app_name='cart_app'
urlpatterns = [

    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),




]

ecommercedress/ecommercedress/fashionstore/fashionstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart_app.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

ecommercedress/ecommercedress/fashionstore/search_app/urls.py
from django.urls import path
from . import views


app_name='search_app'
urlpatterns = [

    path('',views.SearchResult,name='SearchResult'),



]

ecommercedress/ecommercedress/fashionstore/shop/urls.py
from django.urls import path
from . import views


app_name='shop'
urlpatterns = [

    path('',views.allprodCat,name='allprodCat'),
    path('<slug:c_slug>/',views.allprodCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.prodetail,name='prodCatdetail')



]

ecommercedress/ecommercedress/fashionstore/cart_app/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    def Subtotal(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

ecommercedress/ecommercedress/fashionstore/search_app/models.py
from django.db import models

# Create your models here.

ecommercedress/ecommercedress/fashionstore/shop/models.py
from django.db import models

from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering =('name',)
        verbose_name = 'category'
        verbose_name_plural ='categories'

    def __str__(self):
        return '{}'.format(self.name)
    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:prodCatdetail',args=[self.category.slug,self.slug])
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecommercedress/ecommercedress/fashionstore/cart_app/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)

        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart,
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

ecommercedress/ecommercedress/fashionstore/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q


def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommercedress/ecommercedress/fashionstore/shop/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.

def allprodCat(request,c_slug=None):
    c_page =None
    products_list =None
    if c_slug!=None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list= Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def prodetail(request,c_slug,product_slug):
    try:
        products= Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'products':products})

ecommercedress/ecommercedress/fashionstore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>

    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1b99dd44bf.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>


{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</body>
</html>

ecommercedress/ecommercedress/fashionstore/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

         Welcome to the cart store where you can order awesome Dress Collections

{% endblock %}
{% block title %}
   Cart - Order Your Favourite !!!
{% endblock %}
{% block content %}
{% if not cart_items %}
      <div>
          <div class="text-center">
              <br>
              <h1 class="text-center my_title">
                  Your shopping cart is empty
              </h1>
              <br>
              <p class="text-center">
                  Please click<a href="{% url 'shop:allProdCat' %}">Here to continue ordering</a>
              </p>
          </div>

      </div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
             <tr>
                 <td>
                     <a href=""><img src={{cart_item.product.image.url}} class="float-left rounded custom_image"> </a>
                 </td>
                 <td class="text-left">
                     {{cart_item.product.name}}
                     <br>
                     SKU: {{cart_item.product.id}}
                     <br>
                     Unit Price:{{cart_item.product.price}}
                     QTV:{{cart_item.quantity}} x $ {{cart_item.product.price}}
                 </td>
                 <td>$ {{cart_item.sub_total}}</td>
                 {% if cart_item.quantity < cart_item.product.stock %}
                 <td>
                     <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"> +</a>&nbsp;
                     <a href="{% url 'cart_app:cart_remove' cart_item.product.id %}"  class="custom_icon"><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>

                 </td>
                 {% else %}
                 <td>

                     &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}"  class="custom_a"><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>

                 </td>
                 {% endif %}
             </tr>
              {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    please review your shopping cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
            <td class="text-left">
                your total is <strong>${{total}}</strong>
            </td></tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
</div>
    </div>
</div><br>
{% endif %}
{% endblock %}

ecommercedress/ecommercedress/fashionstore/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
    {{category.description|truncatewords:155}}
    {% else %}
        welcome to abc store can buy differnte items...
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
    {{category.name}} -ASTORIA store
    {% else %}
        see your new collection...
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
<div class="row my_row_class">

            <div class="mx-auto">
            <p><a href="{% url 'shop:allprodCat' %}">our product collection</a> </p>
            </div>
</div>

    {% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">



    <br>
<div>
    <h1 class="text-center- my_title"> {{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
    {% else %}
    <div>
        <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products" height="500px" width="1480px">
    </div>
        <br>

    {% endif %}
    <div>
        <h1 class="text-center "> our product collections</h1>
        <p class="text-justify"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>

    </div>
<div>
    <div class="container">
        <div class="row mx_auto">


        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>

            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
            </div>
                    </div>

     {% endfor %}
  </div>
        <div class="max-auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}"   class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                {% endfor %}

</div>
            {% endif %}
        </div>
    {% endblock %}
    </div>
</div>
</div>
</div>

ecommercedress/ecommercedress/fashionstore/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">@ copy; ABC tech pvt.All rights reserved</p>
</div>

ecommercedress/ecommercedress/fashionstore/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allprodCat' %}"><img src="{% static 'img/logo.png' %}"width="130px" height="130px" alt="logoimage"></a>

    </center>
</header>

ecommercedress/ecommercedress/fashionstore/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          shop
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allprodCat' %}">All products</a>
            {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}

        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:allprodCat' %}"><i class="fas fa-shopping-cart">{{item_count}}</i></a>


      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

ecommercedress/ecommercedress/fashionstore/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {{products.description|truncatewords:155}}
{% endblock %}
  {% block title %}
  {% if category %}
  {{products.name}}
  {% endif %}
  {% endblock %}
{% block content %}
<div class="row my_prod_row_class">
      <div class="mx_auto">
        <p><a href="{% url 'shop:allprodCat' %}">HOME</a> | <a href="{{products.category.get_url}}"></a> | {{products.name}}</p>
      </div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <div style="min-width:18 rem;">
        <img src="{{products.image.url}}" alt="{{products.name}}">

     </div>
      </div>
    <div>
      <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <h1 class="my_prod_title">{{products.name}}</h1>
        <p>${{products.price}}</p>
        <P class="my_title">PRODUCT DESCRIPTION</P>
        <p class="text-justify my_prod_text">{{products.description}}</p>
        {% if products.stock <= 0 %}
        <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
        {% else %}
        <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' product.id %}">ADD TO CART</a>
        {% endif %}

    </div>
  </div>
</div>
</div>
    </div>
{% endblock %}

ecommercedress/ecommercedress/fashionstore/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    WE HAVE VARAITY DRESS COLLECTIONS
{% endblock %}
{% block title %}
    SEARCH
{% endblock %}
{% block content %}
    <div>
        <p class="text-center my_search_text">you have searched for<b>{{query}}</b></p>
    </div>
    <div class="container">
        <div class="row mx_auto">


        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>

            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
            </div>
                    </div>
        </div>
        {% empty %}
            <div class="row mx_auto">
                <p class="text-center my_search_text">No result found</p>

            </div>
        {% endfor %}
    </div>
{% endblock %}